In [2]:
import psycopg2
import pandas as pd

In [3]:
def create_country_stats_table(cur):
    sql_create_country_stats_table = """ 
        CREATE TABLE IF NOT EXISTS country_statistics (
            country text NOT NULL,
            countrycode text NOT NULL, 
            indicator_name text, 
            indicator_code text NOT NULL, 
            most_recent_value float,
            year integer,
            gid text[] NOT NULL,
            UNIQUE (country, countrycode, year, indicator_code),
            PRIMARY KEY (country, countrycode, year, indicator_code)
        )"""

    cur.execute(sql_create_country_stats_table)

    print("country_statistics table created")

In [4]:
def drop_country_stats_table(cur):
    sql_drop_country_stats_table = """DROP TABLE country_statistics"""
    
    try:
        cur.execute(sql_drop_country_stats_table)
        conn.commit() 
        print("country_statistics table deleted")
    except:
        print("country_statistics not present")

In [5]:
def import_data(cur,data):
    
    INSERT_STATEMENT = 'INSERT INTO country_statistics \
                            (country, countrycode,  \
                             indicator_name, indicator_code, \
                             most_recent_value, year, \
                             gid) \
                        VALUES (%s, %s, \
                                %s, %s, \
                                %s, %s, \
                                %s);'
    

    for idx, row in data.iterrows():
        print(idx)
        cur.execute(INSERT_STATEMENT, (row['Country Name'], row['Country Code'], 
                                       row['Indicator Name'], row['Indicator Code'], 
                                       row['Most Recent Value'], row['Year'],
                                       row['GID']))

# Load the data

In [12]:
wb_data = pd.read_csv("out/wb_out_FULL.csv")
# convert the GID to list
wb_data.GID = wb_data.GID.apply(lambda x: [x])
wb_data

,Country Name,Country Code,Indicator Name,Indicator Code,Most Recent Value,Year,GID
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.770000e+01,2017.0,[AFG]
1,Afghanistan,AFG,Adequacy of social insurance programs (% of to...,per_si_allsi.adq_pop_tot,1.569503e+01,2007.0,[AFG]
2,Afghanistan,AFG,"Adjusted net enrollment rate, primary (% of pr...",SE.PRM.TENR,2.676600e+01,1993.0,[AFG]
3,Afghanistan,AFG,"Adjusted net enrollment rate, primary, female ...",SE.PRM.TENR.FE,1.369764e+01,1993.0,[AFG]
4,Afghanistan,AFG,"Adjusted net enrollment rate, primary, male (%...",SE.PRM.TENR.MA,3.879503e+01,1993.0,[AFG]
...,...,...,...,...,...,...,...
14185,Zimbabwe,ZWE,Surface area (sq. km),AG.SRF.TOTL.K2,3.907600e+05,2018.0,[ZWE]
14186,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4.650663e+06,2018.0,[ZWE]
14187,Zimbabwe,ZWE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,3.220900e+01,2018.0,[ZWE]
14188,Zimbabwe,ZWE,Urban population growth (annual %),SP.URB.GROW,1.323892e+00,2018.0,[ZWE]
14189,Zimbabwe,ZWE,"Vulnerable employment, total (% of total emplo...",SL.EMP.VULN.ZS,6.473900e+01,2019.0,[ZWE]

# Create the table and upload the data

In [ ]:
# Connect to covid19db.org
conn = psycopg2.connect(
    host='covid19db.org',
    port=5432,
    dbname='covid19db_adm_play',
    user='covid19db_adm_rw',
    password='fGt962FdeG2yXj3c4d3'
)

cur = conn.cursor()

drop_country_stats_table(cur)
conn.commit()


create_country_stats_table(cur)
conn.commit()

# there are 14190 rows 
import_data(cur, wb_data)
conn.commit()

# Test

In [9]:
cur.execute("""SELECT * FROM country_statistics""")

data = pd.DataFrame(cur.fetchall(), columns=[desc[0] for desc in cur.description])
data

,country,countrycode,indicator_name,indicator_code,most_recent_value,year,gid
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.770000e+01,2017,AFG
1,Afghanistan,AFG,Adequacy of social insurance programs (% of to...,per_si_allsi.adq_pop_tot,1.569503e+01,2007,AFG
2,Afghanistan,AFG,"Adjusted net enrollment rate, primary (% of pr...",SE.PRM.TENR,2.676600e+01,1993,AFG
3,Afghanistan,AFG,"Adjusted net enrollment rate, primary, female ...",SE.PRM.TENR.FE,1.369764e+01,1993,AFG
4,Afghanistan,AFG,"Adjusted net enrollment rate, primary, male (%...",SE.PRM.TENR.MA,3.879503e+01,1993,AFG
...,...,...,...,...,...,...,...
14185,Zimbabwe,ZWE,Surface area (sq. km),AG.SRF.TOTL.K2,3.907600e+05,2018,ZWE
14186,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4.650663e+06,2018,ZWE
14187,Zimbabwe,ZWE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,3.220900e+01,2018,ZWE
14188,Zimbabwe,ZWE,Urban population growth (annual %),SP.URB.GROW,1.323892e+00,2018,ZWE
14189,Zimbabwe,ZWE,"Vulnerable employment, total (% of total emplo...",SL.EMP.VULN.ZS,6.473900e+01,2019,ZWE